import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/features/sidebar/components/app-sidebar";
import { SocialBar } from "@/features/sidebar/components/social-bar";
import { SOCIALS } from "@/features/sidebar/lib/socials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Display font for the sidebar brand title.
const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} h-full antialiased`}
    >
      <body className="h-full">
        <div className="flex h-screen overflow-hidden">
          <AppSidebar />
          {/* relative so a full-bleed child (e.g. the home cube) can fill it. */}
          <main className="relative min-w-0 flex-1 overflow-hidden">
            {children}
          </main>
          <SocialBar
            socials={SOCIALS}
            className="sidebar-social flex flex-col items-center justify-center gap-6"
          />
        </div>
      </body>
    </html>
  );
}
